name: "react-native-build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  compile:
    runs-on: macos-11
    timeout-minutes: 60
    env:
      BUILDCACHE_DIR: ../custom_buildcache_dir # will override default location
      BUILDCACHE_LOG_FILE: ../custom_buildcache.log # will override default location
      BUILDCACHE_DEBUG: 3 # will override default of 2
      BUILDCACHE_MAX_CACHE_SIZE: 234567890 # will override default of 500000000
      BUILDCACHE_MAX_LOCAL_ENTRY_SIZE: 34567890 # Not used by buildache-action, but will pass through...
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true

      - uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - uses: ./
        with:
          install_dir: ../custom_install_location # demonstrate override of default location
          cache_key: react-native-compile # demonstrate putting custom key component in cache key
          upload_buildcache_log: true # demonstrate buildcache upload

      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2

      - name: Update Ruby build tools
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: gem update cocoapods

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ github.run_id }}-v1
          restore-keys: ${{ runner.os }}-yarn

      - name: Create React Native Demo
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: npx react-native init demo --skip-install

      - uses: actions/cache@v3
        name: Cache Pods
        id: pods-cache
        with:
          path: demo/ios/Pods
          key: ${{ runner.os }}-pods-v2-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-pods-v2

      - name: Install Demo dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: pushd demo && yarn

      - name: Install Pods
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: pushd demo/ios && pod install

      - name: Build iOS App
        run: |
          which clang
          export SKIP_BUNDLING=1
          set -o pipefail
          xcodebuild CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ -workspace demo/ios/demo.xcworkspace -scheme demo -configuration Debug -sdk iphonesimulator -derivedDataPath demo/ios/build -UseModernBuildSystem=YES
        shell: bash
